version: '3.8'

services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    container_name: atempo-dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ~/.atempo/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ~/.atempo/dnsmasq/conf.d:/etc/dnsmasq.d:ro
    networks:
      - atempo-proxy-network
    environment:
      - HTTP_USER=atempo
      - HTTP_PASS=atempo123
    # Health check to ensure DNS is working
    healthcheck:
      test: ["CMD", "nslookup", "localhost", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  atempo-proxy-network:
    external: true