services:
  # PHP-FPM Service
  app:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    image: {{project}}-app
    container_name: {{project}}-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../../src:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - {{project}}-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: {{project}}-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../../src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - {{project}}-network
    depends_on:
      - app

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: {{project}}-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - {{project}}_mysql_data:/var/lib/mysql
    networks:
      - {{project}}-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: {{project}}-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - {{project}}-network

  # Mailhog Service (for email testing)
  mailhog:
    image: mailhog/mailhog
    container_name: {{project}}-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - {{project}}-network

# Docker Networks
networks:
  {{project}}-network:
    driver: bridge

# Volumes
volumes:
  {{project}}_mysql_data:
    driver: local